field: 09bb940a-c177-4e1b-bf3d-594faa1db71c # Tips Lists
fieldLayouts:
  ee8fb397-21be-4abd-af56-c3ef5b5d51f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 81c72960-efbe-4589-806e-2dc615331bbc # Left List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9faeb27f-9778-4af0-89cc-e274c60e27ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03714fab-501a-4836-8b21-d3a56b7c6f22 # Right List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ccc1d06-3446-4a51-8e39-20d1f4395545
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c8610edd-b58c-474e-8b91-9ef3529b7bdf
        userCondition: null
fields:
  81c72960-efbe-4589-806e-2dc615331bbc: # Left List
    columnSuffix: vecwgpdx
    contentColumnType: text
    fieldGroup: null
    handle: leftList
    instructions: null
    name: 'Left List'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Item Name'
                -
                  - handle
                  - itemName
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  03714fab-501a-4836-8b21-d3a56b7c6f22: # Right List
    columnSuffix: fsjmwumc
    contentColumnType: text
    fieldGroup: null
    handle: rightList
    instructions: null
    name: 'Right List'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Item Name'
                -
                  - handle
                  - itemName
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: lists
name: Lists
sortOrder: 1
