field: d2d0d654-161f-48b1-ab4c-bb2dce41caf0 # Video List Block
fieldLayouts:
  c88488b9-3783-4c58-be82-128827d7f258:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bd430198-a5ad-4c10-a6f4-60acc5a43831 # List Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75139e75-0fd1-4cf1-b76c-5964c4ace904
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8927f746-2885-432f-9f90-cb1c5eb8d630 # List Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bfe75ee-3a19-45a0-a4f2-c34b6d13d809
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60c95d1f-9e3f-49e4-8a22-620e65120008
        userCondition: null
fields:
  8927f746-2885-432f-9f90-cb1c5eb8d630: # List Items
    columnSuffix: ejydgbpd
    contentColumnType: text
    fieldGroup: null
    handle: listItems
    instructions: null
    name: 'List Items'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Text
                -
                  - handle
                  - text
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  bd430198-a5ad-4c10-a6f4-60acc5a43831: # List Title
    columnSuffix: lsmvecbh
    contentColumnType: text
    fieldGroup: null
    handle: listTitle
    instructions: null
    name: 'List Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: videoListBlock
name: 'Video List Block'
sortOrder: 1
