fieldLayouts:
  4bad4fd2-3d12-4c91-9d56-00e22ed83c40:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 34fea8d7-1500-4f12-9119-6022551f17e1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b92ad6c9-7d4b-4947-81d1-8759456ff662
        userCondition: null
fs: assetBase
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
