columnSuffix: null
contentColumnType: string
fieldGroup: 1cb33589-c021-4184-8b3d-a7d14847b35f # Home page
handle: heroLeftContent
instructions: null
name: 'Hero Left Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_heroleftcontent}}'
  maxBlocks: 4
  minBlocks: 0
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
