columnSuffix: null
contentColumnType: string
fieldGroup: 1cb33589-c021-4184-8b3d-a7d14847b35f # Home page
handle: heroButton
instructions: null
name: 'Hero Button'
searchable: false
settings:
  contentTable: '{{%matrixcontent_herobutton}}'
  maxBlocks: 2
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
