columnSuffix: null
contentColumnType: string
fieldGroup: 1cb33589-c021-4184-8b3d-a7d14847b35f # Home page
handle: whereToBuyCards
instructions: null
name: 'Where To Buy Cards'
searchable: false
settings:
  contentTable: '{{%matrixcontent_wheretobuycards}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
