fieldLayouts:
  eaef5a1a-8143-4f97-9180-f4ac1aec7c5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e7b29439-d9b6-49b5-a061-7b8133633f3f # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b78e85e-88b2-437b-9d11-f23b9d6c827f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 468aa095-05d4-4f05-a80f-03599be3d193
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
