defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  3434491c-842d-429e-a8b3-fba8f1b0a691: # DAP
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
